adulau/ssldump

base/pcap-snoop.c, base/tcpconn.c
Avoids wrong cleaning of first connection(s)
=> [bugfix] Initialize initial reference timeval

ssl/ssldecode.c
Fix a null pointer dereference bug of tls12_prf be caused by invalid extern declaration for digests variable.
=> Fix a null pointer dereference bug

configure
Blame on me because the "arch" is hardcoded, but now compile on Ubuntu and Fedora :smile:
=> updated configure for new libpcap location on most linux distro

CREDITS, ChangeLog, base/network.c
can not parse tcp packets and decode application data due to miscalculation of packet length.
=> Fix packet length calculation if IP length is 0, due to TSO

ssl/ssl_analyze.c
- fix miss calculation of read_left if queue already has some data, which might not be bigger than ssl_header_size
- update q->ptr only if q->data is changed
=> fix ssl record queue data read

ssldump.1
Delete the extra "to" in "To decrypt traffic to to host" under the examples section.
=> Fix a typo in the man page

ssl/ssl.enums.c, ssl/ssl_analyze.c, ssl/ssl_h.h, ssl/ssl_rec.c, ssl/ssldecode.c, ssl/ssldecode.h
This is intended to add support for TLS extensions. In addition to displaying the extensions as part of the output of the ClientHello and ServerHello handshake messages, this pull request adds additional support for the following extensions
1. Extended Master Secret and Session Hash [RFC 7627](https://tools.ietf.org/html/rfc7627)
2. Encrypt-then-MAC [RFC 7366](https://tools.ietf.org/html/rfc7366)
3. Server Name Indication [RFC 6066](https://tools.ietf.org/html/rfc6066#section-3)
Please let me know if you see any issues or would like me to make any additional modifications.
=> Tls extensions

ssl/ssl.enums.c
Fixes a compile error on Mac by adding explicit types for the parameters in the forward function declaration.
=> Explicit parameter types for static prototypes

ssl/ssl.enums.c, ssl/ssldecode.c, ssl/ssldecode.h
now you can use NSS keylog to decrypt pcap with resumed sessions (i think must work for many ticket and every sessions id).
=> add support to decrypt resumed sessions

base/network.c, base/tcppack.c, ssl/ssl.enums.c
Fix multiple segfaults on out-of-bounds read access.
Tested with fuzzed pcap files, probably also reachable via live capture.
=> Fix multiple segfaults on out-of-bounds read access

base/network.c, base/network.h, base/pcap-snoop.c, base/proto_mod.h, base/tcpconn.c, base/tcpconn.h, base/tcppack.c, null/null_analyze.c, pcap/pcap_logger.c, ssl/ssl_analyze.c
=> Add support for IPv6 traffic dump

common/include/r_macros.h
ssldecode.c:1101 MAX is used in expression and 0x40 is part of a in the macro
Example tls1.2 pcap and key not decrypting: [tlsv12.zip](https://github.com/adulau/ssldump/files/8761081/tlsv12.zip)
=> Add parentheses around MAX and MIN

ssl/ssldecode.c
c_mk and s_mk is only set for non aead ciphers at line 970 hence check before printing
<details>
<summary> Example seg fault </summary>
[out_tls12.zip](https://github.com/adulau/ssldump/files/8888745/out_tls12.zip)
```
./ssldump -S crypto -r out_tls12.pcap -l keys.txt
New TCP connection #1: localhost(44662) <-> localhost(4433)
1 1  0.0001 (0.0001)  C>S  Handshake
ClientHello
Version 3.3
cipher suites
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8
TLS_ECDHE_ECDSA_WITH_AES_256_CCM
TLS_DHE_RSA_WITH_AES_256_CCM_8 …
```
=> Print MAC keys only for non AEAD ciphers

ssl/sslprint.c
This should hopefully properly fix what CodeQL analysis spotted in #67. However, please review carefully!
I am not a C programmer or expert, but from my understanding, `time_t tv_sec` can be up to `long long`, e.g. on OpenBSD to cover Y2K38 compatibility on 32 bit systems. At https://man.openbsd.org/clock_gettime.2#EXAMPLES, there is an example, which this pull request is inspired from.
See also: https://lists.samba.org/archive/samba-technical/2015-September/109355.html
=> For Y2K38 on 32 bit systems `time_t tv_sec` can be `long long`

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, README.md
- LGTM.com was shut down in December 2022 and recommended to use GitHub code scanning instead
- Possible results from CodeQL analysis will be listed at https://github.com/adulau/ssldump/security
See also: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
=> Add CodeQL analysis

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
With commit #66, I accidentially switched from libssl-dev to libtls-dev. However, ssldump depends on OpenSSL, which is libssl-dev. The libtls-dev package belongs to LibreTLS, which is a port of libtls from LibreSSL to OpenSSL (thus, in the end the correct dependency was installed indirectly, but let's do it right).
=> CI: libtls-dev → libssl-dev

README.md
Fix typo, mention RHEL derivative
=> Fix typo, mention RHEL derivative

.github/workflows/build.yml
Use latest available compilers to catch possibly new build failures early.
=> Switch to gcc-12 (default: gcc-11), clang-14 is newest in ubuntu-latest

CMakeLists.txt
Use correct cmake `GNUInstallDirs` variables with their built-in defaults. `GNUInstallDirs.cmake` expects that at least one language is enabled before including `GNUInstallDirs`.
See also: https://cmake.org/cmake/help/latest/command/install.html
My suggested changes, required to build `ssldump` successfully for Fedora and EPEL, are inspired from [baresip](https://github.com/baresip/baresip/blob/main/CMakeLists.txt) and [librsync](https://github.com/librsync/librsync/blob/master/CMakeLists.txt).
=> Use correct cmake GNUInstallDirs variables with their built-in defaults

base/pcap-snoop.c.in, base/tcpconn.c, base/tcpconn.h, build.sh, ssl/ssl.enums.c, ssldump.1, ssldump.md
This PR adds the possibility to list currently tracked connections by sending a USR1 signal to the ssldump process.
USR2 signal will purge the internal connection tracking structures.
The output is printed on stderr.
A few other messages are now also printed on stderr (along with a startup banner à la  tcpdump).
=> Connection tracker live list & purge

CMakeLists.txt
Implement 2 cmake options:
- `DEBUG_BUILD` adds `-ggdb3 -DDEBUG` to CFLAGS
- `DISABLE_OPTIMIZATION` change optimization level from `-O2` to `-O0`.
Usage:
`$ cmake -B build -G Ninja -DDEBUG_BUILD=ON -DDISABLE_OPTIMIZATION=ON`
*Note*: `-g` and `-02` compiler options are now used by default
This PR supersedes https://github.com/adulau/ssldump/pull/87
=> Implement compilation options

base/pcap-snoop.c.in
- there is no need to deal with L2 as it's not even there
=> base: add support for "raw ip" captures

base/pcap-snoop.c.in
This PR supersede https://github.com/adulau/ssldump/pull/88
It sets packet type to IPv4 or IPv6 based on first nibble of RAW packets (no L2 header).
=> Set packet type for RAW PCAPs

pcap/pcap_logger.c
The fdatasync call generates a `implicit declaration of function 'fdatasync' is invalid in C99` warning when building for macOS (it's nowhere to be found in the system includes), but linking will eventually work fine because there is an unrelated syscall by the same name (different prototype), so it's not doing what it should. So lets not use it.
=> Fix problematic fdatasync() call on macOS

pcap/logpkt.c, pcap/logpkt.h, pcap/pcap_logger.c
I suggest to change PCAP logger code cause of bad timestamps. Timeofday-generated timestamps are not so good for zeek or any dpi parsing (the packages are not in the right order). Also original timestamps seems to be better in PCAP cause it helps to see the real time of the package (for example in Wireshark).
For example on one malware traffic (Smert Ransomware):
PCAP source: https://app.any.run/tasks/5b2f8a32-62ea-47b1-9c3a-b9b474fb0774/
Original pcap timestamps (Wireshark with SSLKeyLogFile specified in settings):
Current ssldump version (gettimeofday-generated timestamps - decrypted at 7 Aug):
This PR's version:
This feature may be very helpful for some malware traffic analysts in future and seems to be more correctly. Please correct me if I'm wrong somewhere.
=> Original PCAP timestamps instead of timeofday-generated

ssl/ssldecode.c, ssl/sslprint.c
Hi! I suggest to change:
1) ssldecode code because of segmentation fault on this one pcap:
https://app.any.run/tasks/90ff9de3-440f-4f5a-8f01-edd8d219def8
2) sslprint code because of TLSv1.3 garbage in flow after decryption (TLS and decrypted traffic mix). This problem is caused by possible bug of ct getting. Maybe @lord8266 will correct me.
https://app.any.run/tasks/db11da7d-817c-4364-a15a-38011f8e5129
Changes:
1) Cause of segfault in ssldecode
Resolved:
2) After decryption TCP stream now not have unnecessary data (like TLS and SSL certificates and bytes that are not related to the original decrypted information):
I tested these changes on many pcaps and these problems no longer appeared.
=> TLSv1.3 garbage in flow fix and segmentation fault fix
